// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/index.ts";
import * as $3 from "./routes/greet/[name].tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/service_worker.ts";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Feed.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/index.ts": $2,
    "./routes/greet/[name].tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/service_worker.ts": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Feed.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
